# This is necessary until https://github.com/travis-ci/travis-ci/issues/3120 is
# fixed
sudo: required

language: scala

env:
  - SKIP_FLAKY=true

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.10.6
  - 2.11.7

jdk:
  - oraclejdk7
  # Note: not currently testing on JDK 8 internally
  - oraclejdk8
  - openjdk7

notifications:
  hipchat:
    rooms:
      secure: ip7yYXJllgMZEwkDNgEfcFUmVtJlGzW3eC+x/NHZWUe7aFTbD/+Who31EWLU28fU9O9FdQquzL96oEQMyD+d+Cy03EhboOJf1f/oKinT1UXNvcx+kf912EgaU8ei4ZQ/o5oc7A+sTyq3wA/FSm/BwhUOjSDFZ4oOTZZXxoZYvYc=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION update

script: ./sbt ++$TRAVIS_SCALA_VERSION coverage test && ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: ./sbt ++$TRAVIS_SCALA_VERSION coveralls
